
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xdfokaaapberzycmsacx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhkZm9rYWFhcGJlcnp5Y21zYWN4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0OTg4MjMsImV4cCI6MjA2MTA3NDgyM30.mCJ5Lmawer_kmFLx3JVzO1VIKKF3yoLapxFY2C-f870";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: window.localStorage,
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: true
  }
});
